/**
* 接口配置文件
*
{"name":"纯净/B站","category":"1","url":"https://z1.m1907.cn/?jx="},
{"name":"高速接口","category":"1","url":"https://jsap.attakids.com/?url="},
{"name":"综合/B站1","category":"1","url":"https://vip.parwix.com:4433/player/?url="},
{"name":"OK解析","category":"1","url":"https://okjx.cc/?url="},
{"name":"乐多资源","category":"1","url":"https://api.leduotv.com/wp-api/ifr.php?isDp=1&vid="},
{"name":"诺诺","category":"1","url":"https://www.ckmov.com/?url="},
{"name":"虾米","category":"1","url":"https://jx.xmflv.com/?url="},
{"name":"全民","category":"1","url":"https://jx.quanmingjiexi.com/?url="},
{"name":"七哥","category":"1","url":"https://jx.mmkv.cn/tv.php?url="},
{"name":"冰豆","category":"1","url":"https://api.qianqi.net/vip/?url="},
{"name":"迪奥","category":"1","url":"https://123.1dior.cn/?url="},
{"name":"CK","category":"1","url":"https://www.ckplayer.vip/jiexi/?url="},
{"name":"LE","category":"1","url":"https://lecurl.cn/?url="},
{"name":"ckmov","category":"1","url":"https://www.ckmov.vip/api.php?url="},
{"name":"ccyjjd","category":"1","url":"https://ckmov.ccyjjd.com/ckmov/?url="},
{"name":"RDHK","category":"1","url":"https://jx.rdhk.net/?v="},
{"name":"爱豆","category":"1","url":"https://jx.aidouer.net/?url="},
{"name":"H8","category":"1","url":"https://www.h8jx.com/jiexi.php?url="},
{"name":"BL","category":"1","url":"https://vip.bljiex.com/?v="},
{"name":"解析la","category":"1","url":"https://api.jiexi.la/?url="},
{"name":"MUTV","category":"1","url":"https://jiexi.janan.net/jiexi/?url="},
{"name":"MAO","category":"1","url":"https://www.mtosz.com/m3u8.php?url="},
{"name":"老板","category":"1","url":"https://vip.laobandq.com/jiexi.php?url="},
{"name":"盘古","category":"1","url":"https://www.pangujiexi.cc/jiexi.php?url="},
{"name":"盖世","category":"1","url":"https://www.gai4.com/?url="},
{"name":"小蒋","category":"1","url":"https://www.kpezp.cn/jlexi.php?url="},
{"name":"YiTV","category":"1","url":"https://jiexi.us/?url="},
{"name":"星空","category":"1","url":"http://60jx.com/?url="},
{"name":"0523","category":"1","url":"https://go.yh0523.cn/y.cy?url="},
{"name":"17云","category":"1","url":"https://www.1717yun.com/jx/ty.php?url="},
{"name":"4K","category":"1","url":"https://jx.4kdv.com/?url="},
{"name":"云析","category":"1","url":"https://jx.yparse.com/index.php?url="},
{"name":"8090","category":"1","url":"https://www.8090g.cn/?url="},
{"name":"江湖","category":"1","url":"https://api.jhdyw.vip/?url="},
{"name":"诺讯","category":"1","url":"https://www.nxflv.com/?url="},
{"name":"PM","category":"1","url":"https://www.playm3u8.cn/jiexi.php?url="},
{"name":"奇米","category":"1","url":"https://qimihe.com/?url="},
{"name":"思云","category":"1","url":"https://jx.ap2p.cn/?url="},
{"name":"听乐","category":"1","url":"https://jx.dj6u.com/?url="},
{"name":"aijx","category":"1","url":"https://jiexi.t7g.cn/?url="},
{"name":"夜幕","category":"1","url":"https://www.yemu.xyz/?url="},
{"name":"52","category":"1","url":"https://vip.52jiexi.top/?url="},
{"name":"黑米","category":"1","url":"https://www.myxin.top/jx/api/?url="},
{"name":"豪华啦","category":"1","url":"https://api.lhh.la/vip/?url="},
{"name":"凉城","category":"1","url":"https://jx.mw0.cc/?url="},
{"name":"33t","category":"1","url":"https://www.33tn.cn/?url="},
{"name":"180","category":"1","url":"https://jx.000180.top/jx/?url="},
{"name":"无名","category":"1","url":"https://www.administratorw.com/video.php?url="},
{"name":"黑云","category":"1","url":"https://jiexi.380k.com/?url="},
{"name":"九八","category":"1","url":"https://jx.youyitv.com/?url="},

{"name":"综合线路解析","category":"2","url":"https://www.showxi.xyz/mov/s/?sv=3&url="},
{"name":"纯净/B站","category":"2","url":"https://z1.m1907.cn/?jx="},
{"name":"高速接口","category":"2","url":"https://jsap.attakids.com/?url="},
{"name":"综合/B站1","category":"2","url":"https://vip.parwix.com:4433/player/?url="},
{"name":"OK解析","category":"2","url":"https://okjx.cc/?url="},
{"name":"乐多资源","category":"2","url":"https://api.leduotv.com/wp-api/ifr.php?isDp=1&vid="},
{"name":"诺诺","category":"2","url":"https://www.ckmov.com/?url="},
{"name":"虾米","category":"2","url":"https://jx.xmflv.com/?url="},
{"name":"全民","category":"2","url":"https://jx.quanmingjiexi.com/?url="},
// {"name":"M3U8","category":"1","url":"https://jx.m3u8.tv/jiexi/?url="},
//{"name":"大白","category":"1","url":"https://api.myzch.cn/?url="},
//{"name":"云点播","category":"1","url":"https://api.iopenyun.com:88/vip/?url="},
//{"name":"虾米","category":"1","url":"https://jx.xmflv.com/?url="},
//{"name":"沐白","category":"1","url":"https://www.miede.top/jiexi/?url="},
//{"name":"久播","category":"1","url":"https://jx.jiubojx.com/vip.php?url="},
//{"name":"SMYS","category":"1","url":"https://jxx.smys8.cn/index.php?url="},
//{"name":"明日","category":"1","url":"https://jx.yingxiangbao.cn/vip.php?url="},
//{"name":"维多","category":"1","url":"https://jx.ivito.cn/?url="},
//{"name":"星驰","category":"1","url":"https://vip.cjys.top/?url="},
//{"name":"66","category":"1","url":"https://api.3jx.top/vip/?url="},
//{"name":"116","category":"1","url":"https://jx.116kan.com/?url="},
//{"name":"200","category":"1","url":"https://vip.66parse.club/?url="},
//{"name":"月亮","category":"1","url":"https://api.yueliangjx.com/?url="},
//{"name":"小狼","category":"1","url":"https://jx.yaohuaxuan.com/?url="},
* 如希望播放时不呈现广告请自行寻找并使用无广告解析接口
* "//vip.bljiex.com/?v=" 有广告
* 接口不配置时会前往视频源站播放,如腾讯视频、爱奇艺等
**/
    // "//okjx.cc/?url=",
    // "//api.leduotv.com/wp-api/ifr.php?isDp=1&vid=",
    // "//z1.m1907.cn/?jx=",
    // "//jx.4kdv.com/?url=",
    // "//jx.m3u8.tv/jiexi/?url=",
    // "//jsap.attakids.com/?url=",
    // "//jx.rdhk.net/?v=",
    
    // "https://jx.xmflv.com/?url=", （黑名单）
    
            //     {"name": "综合", "type": "1,3", "url": "https://jx.jsonplayer.com/player/?url="},
            // {"name": "CK", "type": "1,3", "url": "https://www.ckplayer.vip/jiexi/?url="},
            // {"name": "YT", "type": "1,3", "url": "https://jx.yangtu.top/?url="},
            // {"name": "Player-JY", "type": "1,3", "url": "https://jx.playerjy.com/?url="},
            // {"name": "yparse", "type": "1,2", "url": "https://jx.yparse.com/index.php?url="},
            // {"name": "8090", "type": "1,3", "url": "https://www.8090g.cn/?url="},
            // {"name": "剖元", "type": "1,3", "url": "https://www.pouyun.com/?url="},
            // {"name": "虾米", "type": "1,3", "url": "https://jx.xmflv.com/?url="},
            // {"name": "全民", "type": "1,3", "url": "https://43.240.74.102:4433?url="},

            // {"name": "爱豆", "type": "1,3", "url": "https://jx.aidouer.net/?url="},
            // {"name": "夜幕", "type": "1,3", "url": "https://www.yemu.xyz/?url="},
            // {"name": "m1907", "type": "1,2", "url": "https://im1907.top/?jx="},

            // {"name": "M3U8TV", "type": "1,3", "url": "https://jx.m3u8.tv/jiexi/?url="},
            // {"name": "冰豆", "type": "1,3", "url": "https://bd.jx.cn/?url="},
            // {"name": "playm3u8", "type": "1,3", "url": "https://www.playm3u8.cn/jiexi.php?url="},
    
jsApiConfig([
    "https://okjx.cc/?url=",
    "https://jx.yangtu.top/?url=",
]);